//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPage_Uploads.DataDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlobRecord
    {
        public int id { get; set; }
        public string blob_name { get; set; }
        public System.DateTime date { get; set; }
        public string url { get; set; }
    }
}
